server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rice_novel?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6666
    jedis:
      pool:
        max-active: 8
        max-wait:  1ms
        max-idle: 4
        min-idel: 0
  elasticsearch:
    rest:
      uris: http://42.194.194.84:9200

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    com.heng.mapper: debug

shiro-redis:
  enabled: true
  redis-manager:
    host: localhost:6666

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥/盐
  secret: yeb-secret
  #JWT的超期限时间（60*60*24）
  expiration: 612800
  #JWT 负载中拿到开头
  tokenHead: Bearer

heng:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 612800
    header: Authorization

